name: generate podcasts feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: setup/setup-python@main
        with:
          python-verson: "3.12"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: run feed generator
        run: feed.py
      - name: push repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github-actions.com
          git add.
          git commit -m "modified feed"
          git push
          
