name: generate podcasts feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Feed Generator
        uses: CharlesInteractor/podcast-generator@main
          
